# Generated by Django 5.1.4 on 2024-12-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='detailed_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
