# Generated by Django 5.1.4 on 2024-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_alter_anime_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
