# Generated by Django 5.1.4 on 2024-12-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0004_anime_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='poster',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='detailed_description',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='release_data',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes_list', to='HOME.anime')),
            ],
        ),
    ]
