# Generated by Django 5.1.4 on 2025-01-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_anime_created_at_episode_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='video_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='kodik_id',
            field=models.CharField(blank=True, help_text='Kodik movie id', max_length=255, null=True),
        ),
    ]
