# Generated by Django 5.1.4 on 2025-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_alter_anime_kodik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='MPAA_rating',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='anime_studio',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
    ]
